trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  outPutDirectory: $(Build.ArtifactStagingDirectory)

steps:

- script: | 
   npm install 
   npm run build 
  displayName: 'build react app' 

- task: ArchiveFiles@2
  displayName: 'Create Zip Package'
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(outPutDirectory)/reactapp.zip'

- task: PublishBuildArtifacts@1
  displayName: Start publish artifacts
  inputs:
    PathtoPublish: '$(outPutDirectory)'
    ArtifactName: 'drop'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '.'
    output_location: 'build'
    skip_app_build: true
    azure_static_web_apps_api_token: $(SWA_TOKEN)

